id: opecha:P004465
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC40
  title: རྒྱུད་ཐམས་ཅད་ཀྱི་རྒྱལ་པོ་དཔལ་གསང་བ་འདུས་པའི་རྩ་བའི་རྒྱུད་ཀྱི་སྒྲོན་མ་རབ་ཏུ་གསལ་བར་བྱེད་པའི་རྒྱ་ཆེར་བཤད་པས་འཆད་པ།
  volume: ''
  author: ''
