id: I912D2A3E
legacy_id: P004465
ocr_import_info:
  bdrc_scan_id: W1AC40
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T16:02:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T18:17:16.491632+00:00'
last_modified: 2022-08-31 02:18:43.127321
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC40
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1AC40
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱུད་ཐམས་ཅད་ཀྱི་རྒྱལ་པོ་དཔལ་གསང་བ་འདུས་པའི་རྩ་བའི་རྒྱུད་ཀྱི་སྒྲོན་མ་རབ་ཏུ་གསལ་བར་བྱེད་པའི་རྒྱ་ཆེར་བཤད་པས་འཆད་པ།
  author: རྗེ་བཙུན་ཤེས་རབ་སེངྒེ
statistics:
  ocr_word_mean_confidence_index: 0.7443257386875388
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I2PD17596:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD17596
      total_pages: 800
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD17596.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.7443257386875388
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
